environment:
    matrix:
        - PYTHON: "C:\\Python27_32"
          PYTHON_VERSION: "2.7"
          PYTHON_ARCH: "32"
          CONDA_PY: "27"
          CONDA_NPY: "18"

#        - PYTHON: "C:\\Python27_64"
#          PYTHON_VERSION: "2.7"
#          PYTHON_ARCH: "64"
#          CONDA_PY: "27"
#          CONDA_NPY: "18"
#
#        - PYTHON: "C:\\Python34_32"
#          PYTHON_VERSION: "3.4"
#          PYTHON_ARCH: "32"
#          CONDA_PY: "34"
#          CONDA_NPY: "18"
#
#        - PYTHON: "C:\\Python34_64"
#          PYTHON_VERSION: "3.4"
#          PYTHON_ARCH: "64"
#          CONDA_PY: "34"
#          CONDA_NPY: "18"



install:
    # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
    # and all required packages
    - powershell .\\ciscripts\\appveyor\\install.ps1
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"


build: false

test_script:
    - python do_io

